import { Injectable, NotFoundException } from '@nestjs/common';
import { DataSource, EntityManager } from 'typeorm';
import { DomainError } from '../common/domain-error';
import { Inventory } from '../inventory/entities/inventory.entity';
import { InventoryMovement, InventoryMovementType } from '../inventory/entities/inventory-movement.entity';
import { ProductVariant } from '../products/entities/product-variant.entity';
import { AdminAuditLog } from './entities/admin-audit-log.entity';
import { AdjustDto, InventoryListDto, MovementListDto, RestockDto } from './admin-inventory.dto';

const missing = () => new NotFoundException({ code: 'INVENTORY_NOT_FOUND', message: 'El inventario de la variante no existe.' });
@Injectable()
export class AdminInventoryService {
  constructor(private readonly dataSource: DataSource) {}
  async list(q: InventoryListDto) { const page = q.page ?? 1, pageSize = q.pageSize ?? 20; const qb = this.dataSource.getRepository(Inventory).createQueryBuilder('inventory').innerJoinAndSelect('inventory.variant', 'variant').innerJoinAndSelect('variant.product', 'product'); if (q.search) qb.andWhere('(product.name ILIKE :search OR variant.name ILIKE :search OR variant.sku ILIKE :search)', { search: `%${q.search.trim()}%` }); if (q.active !== undefined) qb.andWhere('variant.active = :active', { active: q.active }); if (q.lowStock) qb.andWhere('inventory.stock_on_hand - inventory.reserved_stock <= COALESCE(variant.low_stock_threshold, -1)'); if (q.outOfStock) qb.andWhere('inventory.stock_on_hand - inventory.reserved_stock <= 0'); const fields: Record<string,string> = { sku: 'variant.sku', productName: 'product.name', stockOnHand: 'inventory.stock_on_hand', availableStock: 'inventory.stock_on_hand - inventory.reserved_stock' }; const [field, direction] = (q.sort ?? 'sku:asc').split(':'); qb.orderBy(fields[field] ?? fields.sku, direction?.toUpperCase() === 'DESC' ? 'DESC' : 'ASC').skip((page - 1) * pageSize).take(pageSize); const [rows, total] = await qb.getManyAndCount(); return { page, pageSize, total, items: rows.map(i => ({ variantId: i.variantId, productId: i.variant.productId, productName: i.variant.product.name, variantName: i.variant.name, sku: i.variant.sku, active: i.variant.active, stockOnHand: i.stockOnHand, reservedStock: i.reservedStock, availableStock: i.stockOnHand - i.reservedStock, lowStockThreshold: i.variant.lowStockThreshold })) }; }
  private async locked(manager: EntityManager, variantId: string) { const inventory = await manager.createQueryBuilder(Inventory, 'inventory').setLock('pessimistic_write').where('inventory.variant_id = :variantId', { variantId }).getOne(); if (!inventory) throw missing(); const variant = await manager.findOneBy(ProductVariant, { id: variantId }); if (!variant) throw missing(); return { inventory, variant }; }
  private audit(manager: EntityManager, adminId: string, action: string, variant: ProductVariant, previous: number, next: number, quantity: number, reason: string, reserved: number) { return manager.save(AdminAuditLog, { adminUserId: adminId, action, entityType: 'INVENTORY', entityId: variant.id, metadata: { variantId: variant.id, sku: variant.sku, previousStockOnHand: previous, newStockOnHand: next, reservedStock: reserved, quantity, reason } }); }
  async restock(variantId: string, dto: RestockDto, adminId: string) { const reason = dto.reason.trim(); if (!reason) throw new DomainError('INVALID_STOCK_ADJUSTMENT', 'El motivo es obligatorio.', undefined, 400); return this.dataSource.transaction(async m => { const { inventory, variant } = await this.locked(m, variantId); const previous = inventory.stockOnHand; inventory.stockOnHand += dto.quantity; await m.save(inventory); await m.save(InventoryMovement, { variantId, orderId: null, type: InventoryMovementType.RESTOCK, onHandDelta: dto.quantity, reservedDelta: 0, reason }); await this.audit(m, adminId, 'INVENTORY_RESTOCKED', variant, previous, inventory.stockOnHand, dto.quantity, reason, inventory.reservedStock); return inventory; }); }
  async adjust(variantId: string, dto: AdjustDto, adminId: string) { const reason = dto.reason.trim(); if (!reason) throw new DomainError('INVALID_STOCK_ADJUSTMENT', 'El motivo es obligatorio.', undefined, 400); return this.dataSource.transaction(async m => { const { inventory, variant } = await this.locked(m, variantId); if (dto.stockOnHand < inventory.reservedStock) throw new DomainError('STOCK_ADJUSTMENT_CONFLICT', 'El ajuste dejaría stock por debajo de lo reservado.', { variantId, reservedStock: inventory.reservedStock }, 409); const previous = inventory.stockOnHand, delta = dto.stockOnHand - previous; inventory.stockOnHand = dto.stockOnHand; await m.save(inventory); await m.save(InventoryMovement, { variantId, orderId: null, type: InventoryMovementType.ADJUSTMENT, onHandDelta: delta, reservedDelta: 0, reason }); await this.audit(m, adminId, 'INVENTORY_ADJUSTED', variant, previous, inventory.stockOnHand, delta, reason, inventory.reservedStock); return inventory; }); }
  async movements(variantId: string, q: MovementListDto) { if (!await this.dataSource.getRepository(Inventory).existsBy({ variantId })) throw missing(); const page = q.page ?? 1, pageSize = q.pageSize ?? 20, qb = this.dataSource.getRepository(InventoryMovement).createQueryBuilder('movement').where('movement.variant_id = :variantId', { variantId }); if (q.type) qb.andWhere('movement.type = :type', { type: q.type }); if (q.dateFrom) qb.andWhere('movement.created_at >= :from', { from: q.dateFrom }); if (q.dateTo) qb.andWhere('movement.created_at <= :to', { to: q.dateTo }); const [items,total] = await qb.orderBy('movement.created_at', 'DESC').skip((page-1)*pageSize).take(pageSize).getManyAndCount(); return { page, pageSize, total, items }; }
}
